# General parameters
name: "Adult"
output: "scripts/output/"

# Parameters inside the notebook
  # Path from output directory
path: "../data/adult.csv"
read_csv_params:  "sep=','"
target: "income"
env:  ".venv"
privileged_values: {
    'marital-status': ['Married-civ-spouse','Married-AF-spouse'],
    'race': ['White'],
    'gender': ['Male']
}